### ISSUE TITLE
Date/Time header link in TOC broken on awesome-go.com

### ISSUE THREAD

**Issue by willfaught** [avelino/awesome-go#1224] opened 2016-12-14 23:59 UTC
- Date/Time header link in TOC doesn't work
- ORM list appears as a paragraph, not a list

**Comment by shurcooL** [comment] 2016-12-15 01:08
> ORM list appears as a paragraph, not a list

Can't reproduce. It seems fine to me:

![image](https://cloud.githubusercontent.com/assets/1924134/21207918/f88ae568-c238-11e6-887e-4d524f4df2d8.png)

[Goroutines section](https://awesome-go.com/#goroutines), on the other hand, does have an issue:

![image](https://cloud.githubusercontent.com/assets/1924134/21207932/14e5e7c6-c239-11e6-8d54-b9115d7d0eaf.png)

**Comment by willfaught** [comment] 2016-12-15 01:11
Woops, you're right. It was the goroutine section that had the paragraph problem.

**Comment by shurcooL** [comment] 2016-12-15 01:15
Ok, I've fixed that second issue in b9ad39eb9ebe1916b2d9e74bdd038aa00611e74c. Goroutines section now looks okay:

![image](https://cloud.githubusercontent.com/assets/1924134/21208113/faad145a-c239-11e6-9cb1-7ee18ee3a94a.png)

**Comment by willfaught** [comment] 2016-12-15 04:35
Can you not reproduce the link issue?

**Comment by shurcooL** [comment] 2016-12-15 04:42
I can. That's why this issue is still open.

**Comment by shurcooL** [comment] 2016-12-15 04:44
It's not just Date & Time, it's also "Generation & Generics" and any other header with an ampersand. It happens because of the difference in Markdown rendering between github.com and whatever's used on awesome-go.com.

**Comment by shurcooL** [comment] 2017-05-30 21:45
I got an idea for a temporary workaround fix.

We can just rename those heading not to include the problematic `&` symbol. I.e., use "Date and Time" rather than "Date & Time".

It wouldn't completely resolve the issue, but at least fix it for the users. It's easy and quick.

**Comment by cassiobotaro** [comment] 2017-08-27 20:15
Fixed with #1505

**Closed by cassiobotaro** 2017-08-27 20:15 UTC
