### ISSUE TITLE
[awesome-go.com]: Utility/Miscellaneous routes to a 404 page

### ISSUE THREAD

**Issue by flowck** [avelino/awesome-go#4283] opened 2022-06-15 21:46 UTC
The link [Utility/Miscellaneous](https://awesome-go.com/utilitymiscellaneous) routes to a 404 page.

![Screenshot 2022-06-15 at 22 45 09](https://user-images.githubusercontent.com/1679333/173935267-0b3c62dd-a500-4230-ad98-51fee6b648c7.png)

![Screenshot 2022-06-15 at 22 45 52](https://user-images.githubusercontent.com/1679333/173935356-82764937-1eb3-49fe-b9f0-4990b082b211.png)

**Comment by Aminuabdullahi** [comment] 2022-07-01 19:32
Hey am new here 😊

**Comment by benschoch** [comment] 2022-08-30 13:42
As far as I can see, the reason lies in the differing behavior of the markdown parser ([gomarkdown/markdown:sanitizeHeadingID](https://github.com/gomarkdown/markdown/blob/master/parser/block.go#L85-L104)) and the GitHub README rendering.
While GitHub creates `utilitymiscellaneous` as a slug, the markdown library creates `utility-miscellaneous`.
Unfortunately the gomarkdown library does not support a custom method to slugify out of the box.

**Comment by CodeWithSandip47** [comment] 2022-10-02 08:07
- this mischievous have an some *bug* is @ceriath 
- the second one is your reactive and the OS V1.22.11 
   fisher item and the advaced of nature #th

**Comment by r0ushann** [comment] 2022-10-07 10:04
hey @flowck  the issue seems to be resolved as I am being successfully directed to the utility/miscellaneous page.

please check again and if the issue is truely resolved please close the issue! :)

**Closed** 2022-10-07 10:48 UTC
Labels: bug, awesome-go.com
