### ISSUE TITLE
Show Github star count next to project link

### ISSUE THREAD

**Issue by mrichman** [avelino/awesome-go#1373] opened 2017-04-18 19:30 UTC
Show Github star count next to project link

**Comment by shurcooL** [comment] 2017-04-18 19:41
This came up in the past. See #1266.

Also, PR #1368 is relevant.

**Comment by shurcooL** [comment] 2017-04-18 19:42
I'll close this because it's a duplicate of issue #1213, which is still open. I'll rename that one to be more discoverable.

**Closed by shurcooL** 2017-04-18 19:42 UTC
